version: 2

project_name: stick

builds:
  - id: stick
    main: .
    binary: stick

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w
      - -X github.com/hareshkhan01/sticky-notes/cmd.version={{ .Version }}
      - -X github.com/hareshkhan01/sticky-notes/cmd.commit={{ .Commit }}
      - -X github.com/hareshkhan01/sticky-notes/cmd.date={{ .Date }}

archives:
  - formats:
      - tar.gz

    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
